# Usa la imagen oficial de MySQL 8.0
FROM mysql:8.0

# Establece variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=mi_base_de_datos
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=contraseña

# Copia un archivo SQL para inicializar la base de datos
COPY init.sql /docker-entrypoint-initdb.d/

# Expone el puerto 3306
EXPOSE 3306